import Darwin
import Foundation
import SwiftUI
import UIKit

extension HealthDataStore {
  static let baseLandingSnapshots = [
    snapshot(id: "health-monitor", route: .healthMonitor, group: .today, title: "Health Monitor", value: "--", unit: "", status: "No live vitals", freshness: "No local data", provenance: "BLE streams and packet extracts", source: .unavailable("health monitor needs live BLE vitals or packet-derived vitals"), systemImage: "heart.text.square", tint: .red, trendValues: [], range: "No data"),
    snapshot(id: "sleep", route: .sleep, group: .today, title: "Sleep", value: "--", unit: "%", status: "No sleep data", freshness: "No band sleep", provenance: "metrics.sleep_score_from_features", source: .unavailable("sleep requires band sleep packet import"), systemImage: "bed.double", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "recovery", route: .recovery, group: .today, title: "Recovery", value: "--", unit: "%", status: "No data", freshness: "No recovery score", provenance: "metrics.recovery_score_from_features", source: .unavailable("recovery score not available"), systemImage: "battery.100percent", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "strain", route: .strain, group: .training, title: "Strain", value: "--", unit: "", status: "No strain data", freshness: "No local data", provenance: "metrics.strain_score_from_features", source: .unavailable("strain requires packet-derived activity and heart-rate inputs"), systemImage: "figure.run", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "stress", route: .stress, group: .vitals, title: "Stress", value: "--", unit: "%", status: "No HR data", freshness: "No local data", provenance: "goose.stress.hr_proxy.v1", source: .unavailable("stress requires local HR samples"), systemImage: "waveform.path.ecg", tint: .yellow, trendValues: [], range: "No data"),
    snapshot(id: "cardio-load", route: .cardioLoad, group: .training, title: "Cardio Load", value: "--", unit: "load", status: "Needs activity", freshness: "No local data", provenance: "goose.cardio_load.local_v1", source: .unavailable("cardio load needs stored OOPS activity sessions with HR"), systemImage: "heart.circle", tint: .pink, trendValues: [], range: "No data"),
    snapshot(id: "energy-bank", route: .energyBank, group: .today, title: "Energy Bank", value: "--", unit: "%", status: "No stress data", freshness: "No local data", provenance: "goose.energy_bank.local_v1", source: .unavailable("energy bank requires stress windows from HR samples"), systemImage: "bolt.circle", tint: .teal, trendValues: [], range: "No data"),
    snapshot(id: "packet-inputs", route: .packetInputs, group: .algorithms, title: "Packet Inputs", value: "--", unit: "", status: "Not extracted", freshness: "No run", provenance: "metricInputReadinessSummary()", source: .unavailable("packet-derived inputs not extracted"), systemImage: "square.stack.3d.up", tint: .blue, trendValues: [], range: "Run to populate"),
    snapshot(id: "algorithms", route: .algorithms, group: .algorithms, title: "Algorithms", value: "--", unit: "families", status: "Not loaded", freshness: "No bridge catalog", provenance: "algorithmDefinitions", source: .unavailable("metric registry not loaded"), systemImage: "function", tint: .purple, trendValues: [], range: "No data"),
    snapshot(id: "calibration", route: .calibration, group: .algorithms, title: "Calibration", value: "--", unit: "", status: "No labels", freshness: "No run", provenance: "calibrationSummary()", source: .unavailable("calibration requires stored labels and local runs"), systemImage: "slider.horizontal.3", tint: .mint, trendValues: [], range: "No data"),
  ]

  static let baseHealthMonitorSnapshots = [
    snapshot(id: "respiratory-rate", route: .healthMonitor, group: .vitals, title: "Respiratory Rate", value: "--", unit: "rpm", status: "Unavailable", freshness: "Packet proof pending", provenance: "vitalEventFeatureSummary()", source: .unavailable("respiratory packet proof pending"), systemImage: "lungs", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "resting-hr", route: .healthMonitor, group: .vitals, title: "Resting HR", value: "--", unit: "bpm", status: "Unavailable", freshness: "No local data", provenance: "restingHeartRateFeatureSummary()", source: .unavailable("resting HR requires HR samples"), systemImage: "heart", tint: .red, trendValues: [], range: "No data"),
    snapshot(id: "resting-hrv", route: .healthMonitor, group: .vitals, title: "Resting HRV", value: "--", unit: "ms", status: "Unavailable", freshness: "No validated HRV", provenance: "hrvFeatureSummary()", source: .unavailable("HRV requires validated beat-interval evidence"), systemImage: "waveform.path.ecg", tint: .blue, trendValues: [], range: "No data"),
    snapshot(id: "oxygen-saturation", route: .healthMonitor, group: .vitals, title: "Oxygen Saturation", value: "--", unit: "%", status: "Unavailable", freshness: "Packet proof pending", provenance: "vitalEventFeatureProvenanceSummary()", source: .unavailable("SpO2 packet proof pending"), systemImage: "drop", tint: .cyan, trendValues: [], range: "No data"),
    snapshot(id: "wrist-temperature", route: .healthMonitor, group: .vitals, title: "Wrist Temperature", value: "--", unit: "C", status: "Unavailable", freshness: "Packet proof pending", provenance: "vitalEventFeatureProvenanceSummary()", source: .unavailable("temperature packet proof pending"), systemImage: "thermometer.medium", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "health-sleep", route: .sleep, group: .vitals, title: "Sleep", value: "--", unit: "", status: "Unavailable", freshness: "No band sleep", provenance: "sleepFeatureScoreSummary()", source: .unavailable("sleep requires band sleep packet import"), systemImage: "bed.double", tint: .indigo, trendValues: [], range: "No data"),
  ]

  static let sleepTrendRows = [
    snapshot(id: "sleep-score-trend", route: .sleep, group: .today, title: "Sleep Score", value: "--", unit: "%", status: "No data", freshness: "No band sleep", provenance: "sleep score output", source: .unavailable("sleep trend requires band sleep history"), systemImage: "bed.double", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "time-asleep-trend", route: .sleep, group: .today, title: "Time Asleep", value: "--", unit: "", status: "No data", freshness: "No band sleep", provenance: "sleep window", source: .unavailable("time asleep trend requires band sleep history"), systemImage: "clock", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "rem-trend", route: .sleep, group: .today, title: "REM sleep", value: "--", unit: "", status: "No data", freshness: "No stages", provenance: "sleep stages", source: .unavailable("REM trend requires sleep stage output"), systemImage: "moon.zzz", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "deep-trend", route: .sleep, group: .today, title: "Deep Sleep", value: "--", unit: "", status: "No data", freshness: "No stages", provenance: "sleep stages", source: .unavailable("deep sleep trend requires sleep stage output"), systemImage: "moon.stars", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "hr-dip-trend", route: .sleep, group: .today, title: "Heart Rate Dip", value: "--", unit: "%", status: "No data", freshness: "No sleep HR", provenance: "sleep HR", source: .unavailable("heart rate dip requires sleep HR windows"), systemImage: "heart", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "sleep-bank-trend", route: .sleep, group: .today, title: "Sleep Bank", value: "--", unit: "", status: "No data", freshness: "No sleep need", provenance: "sleep debt", source: .unavailable("sleep bank requires sleep need and sleep history"), systemImage: "banknote", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "sleep-time-trend", route: .sleep, group: .today, title: "Sleep Time", value: "--", unit: "", status: "No data", freshness: "No sleep history", provenance: "schedule", source: .unavailable("sleep time trend requires sleep history"), systemImage: "bed.double", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "wake-time-trend", route: .sleep, group: .today, title: "Wake Time", value: "--", unit: "", status: "No data", freshness: "No sleep history", provenance: "schedule", source: .unavailable("wake time trend requires sleep history"), systemImage: "sun.max", tint: .indigo, trendValues: [], range: "No data"),
    snapshot(id: "time-to-fall-asleep-trend", route: .sleep, group: .today, title: "Time To Fall Asleep", value: "--", unit: "", status: "No data", freshness: "Needs labels", provenance: "sleep timeline", source: .unavailable("latency labels pending"), systemImage: "timer", tint: .indigo, trendValues: [], range: "No data"),
  ]

  static let recoveryTrendRows = [
    snapshot(id: "recovery-score-trend", route: .recovery, group: .today, title: "Recovery Score", value: "--", unit: "%", status: "No data", freshness: "No recovery score", provenance: "metrics.recovery_score_from_features", source: .unavailable("recovery score not available"), systemImage: "leaf.fill", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "recovery-hrv-trend", route: .recovery, group: .vitals, title: "Resting HRV", value: "--", unit: "ms", status: "No data", freshness: "No HRV trend", provenance: "metrics.hrv_features", source: .unavailable("HRV trend not available"), systemImage: "waveform.path.ecg", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "recovery-rhr-trend", route: .recovery, group: .vitals, title: "Resting HR", value: "--", unit: "bpm", status: "No data", freshness: "No resting HR trend", provenance: "metrics.resting_hr_features", source: .unavailable("resting HR trend not available"), systemImage: "heart", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "recovery-rr-trend", route: .recovery, group: .vitals, title: "Respiratory Rate", value: "--", unit: "rpm", status: "No data", freshness: "Packet proof pending", provenance: "provided vitals", source: .unavailable("respiratory packet proof pending"), systemImage: "lungs", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "recovery-spo2-trend", route: .recovery, group: .vitals, title: "Oxygen Saturation", value: "--", unit: "%", status: "No data", freshness: "Packet proof pending", provenance: "provided vitals", source: .unavailable("SpO2 packet proof pending"), systemImage: "drop", tint: .green, trendValues: [], range: "No data"),
    snapshot(id: "recovery-temp-trend", route: .recovery, group: .vitals, title: "Wrist Temperature", value: "--", unit: "C", status: "No data", freshness: "Packet proof pending", provenance: "provided vitals", source: .unavailable("temperature packet proof pending"), systemImage: "thermometer.medium", tint: .green, trendValues: [], range: "No data"),
  ]

  static let strainTrendRows = [
    snapshot(id: "strain-score-trend", route: .strain, group: .training, title: "Strain Score", value: "--", unit: "", status: "No data", freshness: "No local data", provenance: "strain score output", source: .unavailable("strain score history unavailable"), systemImage: "figure.run", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "exercise-duration-trend", route: .strain, group: .training, title: "Exercise Duration", value: "--", unit: "min", status: "No data", freshness: "No local data", provenance: "activity sessions", source: .unavailable("activity sessions unavailable"), systemImage: "timer", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "daytime-hr-trend", route: .strain, group: .training, title: "Daytime HR", value: "--", unit: "bpm", status: "No data", freshness: "No local data", provenance: "HR stream", source: .unavailable("daytime HR unavailable"), systemImage: "heart", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "active-energy-trend", route: .strain, group: .training, title: "Active Calories", value: "--", unit: "kcal", status: "No data", freshness: "No local data", provenance: "energy contract", source: .unavailable("active energy unavailable"), systemImage: "flame.fill", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "total-energy-trend", route: .strain, group: .training, title: "Total Energy", value: "--", unit: "kcal", status: "No data", freshness: "No local data", provenance: "energy contract", source: .unavailable("energy unavailable"), systemImage: "flame", tint: .orange, trendValues: [], range: "No data"),
    snapshot(id: "step-count-trend", route: .strain, group: .training, title: "Step Count", value: "--", unit: "", status: "No data", freshness: "No local data", provenance: "step count contract", source: .unavailable("step count unavailable"), systemImage: "shoeprints.fill", tint: .orange, trendValues: [], range: "No data"),
  ]

  static let stressTrendRows = [
    snapshot(id: "stress-score-trend", route: .stress, group: .vitals, title: "Stress Score", value: "--", unit: "%", status: "No data", freshness: "No HR data", provenance: "stress score output", source: .unavailable("stress trend requires HR samples"), systemImage: "waveform.path.ecg", tint: .yellow, trendValues: [], range: "No data"),
    snapshot(id: "non-activity-stress-trend", route: .stress, group: .vitals, title: "Non-Activity Stress", value: "--", unit: "%", status: "No data", freshness: "No HR data", provenance: "activity masking", source: .unavailable("non-activity stress requires HR samples and activity masks"), systemImage: "brain.head.profile", tint: .yellow, trendValues: [], range: "No data"),
    snapshot(id: "sleep-stress-trend", route: .stress, group: .vitals, title: "Sleep Stress", value: "--", unit: "%", status: "No data", freshness: "No sleep windows", provenance: "sleep windows", source: .unavailable("sleep stress requires sleep windows and HR samples"), systemImage: "moon.zzz", tint: .yellow, trendValues: [], range: "No data"),
  ]
}
